### ISSUE TITLE
Batch load script won't upload test + non-test RTs in same batch

### ISSUE THREAD

**Issue by mcm104** [uwlib-cams/sinopia_maps#61]
All while using the same JWT...

- When loading test RTs into Sinopia Stage:
```
LOADING RESOURCE TEMPLATES INTO SINOPIA
========================================

Enter JWT here:
> eyJraWQiOiJ5SnczaUFaOWsrRVdQekxhakVFbVwvM1FzdUZzT0hcL2NucWdyWWhcL2VsRHZvPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI4ZTQ4YWJkYS03ZjA5LTQwMWItODA4Ni01OTcyZmNmZWVjZmMiLCJjb2duaXRvOmdyb3VwcyI6WyJ3YXNoaW5ndG9uIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy13ZXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtd2VzdC0yX2lsTVFXME0wUiIsImNsaWVudF9pZCI6IjIzbDMwcGJ1NzRwdXNnaDdjbXR1ZmI4ZDA1IiwiZXZlbnRfaWQiOiIwZTNiNmZiNi01MGRhLTQxZjQtOTVkMi1iNWI4YzA1MjVkM2UiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjYxMjgyNzEwLCJleHAiOjE2NjEyODYzMTAsImlhdCI6MTY2MTI4MjcxMCwianRpIjoiMzU1MmFjMmMtOTYwMS00ZjkyLWEyNjQtMzNjY2Q0YjM3MmRjIiwidXNlcm5hbWUiOiJtY20xMDQifQ.L6kW4S_0hESIJSxNTbxgRRezAIsEQfWtPHQ6zzKoRU4UFIlo_Q960oHl7SlohOrcDQtOC10463FpRRe5q6cIXESwLPKDg2LHAG2edd-_46HbFmLUpLuqEoB_P_l-Xha07wKWXRbNXmB3uvHyNdXc-gvJ-MTH-idNfXZQINGHKCtQr6P8YB3RI9QzV9VgBNjyHFx1n9OjOZ0K7_O5RJFJNkGauWSlO4WBIBjsJKRvjPnqLXmYQswSQ0l6vTV5xwFYXiikZ7ErSqtdXdua6bJu6z5PWj0yS9w2dG0dh1Su1ecHS1TAGOIdcpy_aq3Rq7yBCQ2sNUaKPGCeONVS1nW7Mg
Load to Development, Stage, or Production?
[1] Development
[2] Stage
[3] Production
> 2
Upload test resource templates?
[1] Upload test RTs only
[2] Upload non-test RTs only
[3] Upload all RTs
> 1
Enter Sinopia user name here:
> mcm104
TEST_UWSINOPIA_WAU_rdaAgent_na_CAMS.rdf: 200
TEST_UWSINOPIA_WAU_rdaExpression_monograph_CAMS.rdf: 200
TEST_UWSINOPIA_WAU_rdaItem_monograph_CAMS.rdf: 200
TEST_UWSINOPIA_WAU_rdaManifestation_monograph_CAMS.rdf: 200
TEST_UWSINOPIA_WAU_rdaNomen_na_CAMS.rdf: 200
TEST_UWSINOPIA_WAU_rdaPlace_na_CAMS.rdf: 200
TEST_UWSINOPIA_WAU_rdaTimespan_na_CAMS.rdf: 200
TEST_UWSINOPIA_WAU_rdaWork_monograph_CAMS.rdf: 200
```

- When loading non-test RTs into Sinopia Stage:
```
LOADING RESOURCE TEMPLATES INTO SINOPIA
========================================

Enter JWT here:
> eyJraWQiOiJ5SnczaUFaOWsrRVdQekxhakVFbVwvM1FzdUZzT0hcL2NucWdyWWhcL2VsRHZvPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI4ZTQ4YWJkYS03ZjA5LTQwMWItODA4Ni01OTcyZmNmZWVjZmMiLCJjb2duaXRvOmdyb3VwcyI6WyJ3YXNoaW5ndG9uIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy13ZXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtd2VzdC0yX2lsTVFXME0wUiIsImNsaWVudF9pZCI6IjIzbDMwcGJ1NzRwdXNnaDdjbXR1ZmI4ZDA1IiwiZXZlbnRfaWQiOiIwZTNiNmZiNi01MGRhLTQxZjQtOTVkMi1iNWI4YzA1MjVkM2UiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjYxMjgyNzEwLCJleHAiOjE2NjEyODYzMTAsImlhdCI6MTY2MTI4MjcxMCwianRpIjoiMzU1MmFjMmMtOTYwMS00ZjkyLWEyNjQtMzNjY2Q0YjM3MmRjIiwidXNlcm5hbWUiOiJtY20xMDQifQ.L6kW4S_0hESIJSxNTbxgRRezAIsEQfWtPHQ6zzKoRU4UFIlo_Q960oHl7SlohOrcDQtOC10463FpRRe5q6cIXESwLPKDg2LHAG2edd-_46HbFmLUpLuqEoB_P_l-Xha07wKWXRbNXmB3uvHyNdXc-gvJ-MTH-idNfXZQINGHKCtQr6P8YB3RI9QzV9VgBNjyHFx1n9OjOZ0K7_O5RJFJNkGauWSlO4WBIBjsJKRvjPnqLXmYQswSQ0l6vTV5xwFYXiikZ7ErSqtdXdua6bJu6z5PWj0yS9w2dG0dh1Su1ecHS1TAGOIdcpy_aq3Rq7yBCQ2sNUaKPGCeONVS1nW7Mg
Load to Development, Stage, or Production?
[1] Development
[2] Stage
[3] Production
> 2
Upload test resource templates?
[1] Upload test RTs only
[2] Upload non-test RTs only
[3] Upload all RTs
> 2
Enter Sinopia user name here:
> mcm104
UWSINOPIA_WAU_rdaAgent_na_CAMS.rdf: 200
UWSINOPIA_WAU_rdaExpression_monograph_CAMS.rdf: 200
UWSINOPIA_WAU_rdaItem_monograph_CAMS.rdf: 200
UWSINOPIA_WAU_rdaManifestation_monograph_CAMS.rdf: 200
UWSINOPIA_WAU_rdaNomen_na_CAMS.rdf: 200
UWSINOPIA_WAU_rdaPlace_na_CAMS.rdf: 200
UWSINOPIA_WAU_rdaTimespan_na_CAMS.rdf: 200
UWSINOPIA_WAU_rdaWork_monograph_CAMS.rdf: 200
```

- When loading all RTs into Sinopia Stage:
```
LOADING RESOURCE TEMPLATES INTO SINOPIA
========================================

Enter JWT here:
> eyJraWQiOiJ5SnczaUFaOWsrRVdQekxhakVFbVwvM1FzdUZzT0hcL2NucWdyWWhcL2VsRHZvPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI4ZTQ4YWJkYS03ZjA5LTQwMWItODA4Ni01OTcyZmNmZWVjZmMiLCJjb2duaXRvOmdyb3VwcyI6WyJ3YXNoaW5ndG9uIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy13ZXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtd2VzdC0yX2lsTVFXME0wUiIsImNsaWVudF9pZCI6IjIzbDMwcGJ1NzRwdXNnaDdjbXR1ZmI4ZDA1IiwiZXZlbnRfaWQiOiIwZTNiNmZiNi01MGRhLTQxZjQtOTVkMi1iNWI4YzA1MjVkM2UiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjYxMjgyNzEwLCJleHAiOjE2NjEyODYzMTAsImlhdCI6MTY2MTI4MjcxMCwianRpIjoiMzU1MmFjMmMtOTYwMS00ZjkyLWEyNjQtMzNjY2Q0YjM3MmRjIiwidXNlcm5hbWUiOiJtY20xMDQifQ.L6kW4S_0hESIJSxNTbxgRRezAIsEQfWtPHQ6zzKoRU4UFIlo_Q960oHl7SlohOrcDQtOC10463FpRRe5q6cIXESwLPKDg2LHAG2edd-_46HbFmLUpLuqEoB_P_l-Xha07wKWXRbNXmB3uvHyNdXc-gvJ-MTH-idNfXZQINGHKCtQr6P8YB3RI9QzV9VgBNjyHFx1n9OjOZ0K7_O5RJFJNkGauWSlO4WBIBjsJKRvjPnqLXmYQswSQ0l6vTV5xwFYXiikZ7ErSqtdXdua6bJu6z5PWj0yS9w2dG0dh1Su1ecHS1TAGOIdcpy_aq3Rq7yBCQ2sNUaKPGCeONVS1nW7Mg
Load to Development, Stage, or Production?
[1] Development
[2] Stage
[3] Production
> 2
Upload test resource templates?
[1] Upload test RTs only
[2] Upload non-test RTs only
[3] Upload all RTs
> 3
Enter Sinopia user name here:
> mcm104
Traceback (most recent call last):
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "003_batch_load_RTs.py", line 152, in <module>
    prompt_jwt()
  File "003_batch_load_RTs.py", line 93, in prompt_jwt
    prompt_platform(jwt)
  File "003_batch_load_RTs.py", line 106, in prompt_platform
    prompt_resources(jwt, sinopia_platform)
  File "003_batch_load_RTs.py", line 116, in prompt_resources
    upload_list(jwt, platform, RT_list)
  File "003_batch_load_RTs.py", line 121, in upload_list
    sorted_dict = sort_list(RT_list)
  File "003_batch_load_RTs.py", line 39, in sort_list
    g.load(f'../{RT}', format='xml')
  File "/home/mcm104/.local/lib/python3.8/site-packages/rdflib/graph.py", line 1085, in load
    self.parse(source, publicID, format)
  File "/home/mcm104/.local/lib/python3.8/site-packages/rdflib/graph.py", line 1078, in parse
    parser.parse(source, self, **args)
  File "/home/mcm104/.local/lib/python3.8/site-packages/rdflib/plugins/parsers/rdfxml.py", line 579, in parse
    self._parser.parse(source)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.8/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.8/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: file:///mnt/c/Users/curin/Documents/Work/sinopia_maps/UWSINOPIA_WAU_rdaAgent_na_CAMS.json:1:0: not well-formed (invalid token)
```

Need to investigate

**Comment by mcm104** [comment]
[Fixed](https://github.com/uwlib-cams/sinopia_maps/commit/1a43bfd7e363e75d21b877db0caf0055b6cd525f) -- seems to have been an order of operations issue where it was catching files that are not Sinopia-compatible.
